name: EmberDeath
version: '${version}'
main: com.aw3ken.emberdeath.EmberDeathPlugin
api-version: '1.13'
author: aw3keN
description: Kicks players after death, plays a death sound, and sends a local death message.
